name: curved_nav
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^9.0.0
  card_loading: ^0.3.2
  change_app_package_name: ^1.5.0
  cloud_firestore: ^5.6.0
  dartz: ^0.10.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  get_storage: ^2.1.1
  google_mobile_ads: ^5.3.1
  hive_flutter: ^1.1.0
  injectable: ^2.0.1
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.19.0
  introduction_screen: ^3.1.16
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  salomon_bottom_bar: ^3.3.2
  share_plus: ^10.1.4
  shared_preferences: ^2.3.4
  table_calendar: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.15
  buttons_tabbar: ^1.3.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  injectable_generator: ^2.0.1

flutter_launcher_icons:

  image_path_android: "assets/logo/png_logo.png"

  android: true
  adaptive_icon_background: "#275df5"
  adaptive_icon_foreground: "assets/logo/png_logo.png"

  min_sdk_android: 21

flutter:

  uses-material-design: true
  assets:
    - assets/svg/
    - assets/user manual/
    - assets/logo/
