name: curved_nav
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.13
  cloud_firestore: ^5.6.0
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  dartz: ^0.10.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.8.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_nav_bar: ^5.0.7
  hive_flutter: ^1.1.0
  horizontal_week_calendar: ^0.0.18
  injectable: ^2.0.1
  injectable_generator: ^2.0.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.3.4
  syncfusion_flutter_datepicker: ^28.1.35
  table_calendar: ^3.1.2

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true
